# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

language: python
# Need to move to python folder before as Travis assumes everything is in root.
before_install: cd py
install:
- pip install -r requirements.txt

# Per Travis documentation: "If you do not provide a script key in a Python
# project, Travis CI prints a message (“Please override the script: key in your
# .travis.yml to run tests.”) and fails the build."

script: nosetests gps_building_blocks

notifications:
  email:
    recipients:
      secure: "vJgOm8jcIG+aKNDbFxqyewuTg5Y2hnz2e8ZGcrJezjAE/33UHtlnTFZ0zD+2jcLX53EI0QnpbThcWcux+3l4onmtfLMNu2W2G1Q9CG1pxSJZ/jwAulbofalYGp0VZ75/1rW6uWzpKlHkmBvo9R1fL7axlx/0aln0TMGrx9Ti20AzmEyoZhYdv6h7FZuMX8jJBlcUdxnr+w/r/6wbadsJ/iZwCx4DIpJbK7QoQ1Twrf3cc0YGBS9ZU8LsPUxmHZWyiKGkAd7AxgCsM7M7g/F1J2uNzPR7unRQwKpFg8ChPq3Iw2L7q1vJ1qQRLNrFjjB56mbwU5hWOZJ9ptTfSdjk363WkZTuGO1t06hVTtEOvzjzRO4sHgcY83jy3VsxBBR63xv4jCzrmnf50QGuzoge9mn8GowhS4Ep3O75GbC6ETMBy+jYiT0uyabvQXZWRpffrLNAVw+NSnMWvg8nIUaf+eU052QWVymrc7zAaMRCk6P1LrVKn3+iMWWz2garEkfZmLlS65tt9qYQrKSZxmnF84AYnPKi2zW91sORqAs84K3xYMLkV+duQzHx3lnc+7eXGe/nSBJgf6pi58Dqi/XSkW+TdmsDoH/xpiASQEhFYAASzfWC5phx9v+bRfUmZr+XHnHPaPfAlCWRcZao/SbQ5vdFysTcl2l8VTBipw1yTlI="
    on_success: never
    on_failure: always

deploy:
  provider: pypi
  username: __token__
  distributions: sdist bdist_wheel
  password:
    secure: "YW8b+Ie/SdQZh1g7S1XDypyDu750F/wa4ASydSwCNU//osEveFr2vdwo0oldV0iFsj1dFuJaRMEvw5RLlFExrCBseuudRwPJ/RrYKQNEbSHqdxy9fPzFqdtLZcIPOw0Ln7tOf/Mf4EO14hDFeaSz61lD13z5Wnerga5iyB20+d7zpNgC2LugiYX9c5pT8mW9mddpEtTfPMQcIDmlsV8iB7VQVKoK++71pO/DLKnbQrX53FzRs/nMW/l8F1x85Bwh7D39cYLPYuQD3wQzSz9PwGWkPA9PekWe09JleUk4o40iZOJdVqr2LqqHXFO8B4rX4W5FCoSaGNWdoNNtgGhGc64vUOs4dy/oSulff6hvB97NodZevBswDEZWvMbGawxfo28C3LgZGAnkMNf0gWutASItO9oN0BoKGRZQE6daP1qFzprOMwqtK73le5CkNeKT/NvibP4NXtT4klbkjorOmVGJvOqm9KeOo/UQp8SZ5VYS91bGBfopgwTu3WFhoehRmgoCrxdIEJJkE3j7MrxjkZdY4NY5jy3mP+vJU8Y7i3iP9d2yU0ZRC67p64u/mAnClq6/ckeHPbG3chWhAj/xLjt0Hi3C0ePDcgZEUixfBfBfdUOdp7Hv4Ib39agatNypgu6Pq7qGTrdSs8YovBvjSL/xIc3ttGwwgR/NcmyB11g="
  on:
    tags: true
    branch: master
    condition: $TRAVIS_TAG =~ ^release-.*$
